name: PhotographyClient-cd-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-publish:
    uses: richardjanssen/SharedWorkflows/.github/workflows/angular-build-test-publish.yml@main
    with:
      app-name: PhotographyClient
      
  deploy-run:
    needs: build-test-publish
    uses: richardjanssen/SharedWorkflows/.github/workflows/linux-vps-deploy-run-v2.yml@main
    with:
      app-name: PhotographyClient
      is-service: false
      remove-target-folder: true
    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      ssh-key: ${{ secrets.SSHKEY }}
      ssh-passphrase: ${{ secrets.SSHPASSPHRASE }}
